### ISSUE TITLE
gradlew build error

### ISSUE THREAD

**Issue by pilgun** [natanieljr/droidmate#11]
Could not build project because de.tud.sse:soot-infoflow-android:2.7.2-SNAPSHOT is not available at Maven repository.

`> gradlew build` output:
-------------------
FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':distTar'.
Could not resolve all task dependencies for configuration ':runtimeClasspath'.
Could not resolve de.tud.sse:soot-infoflow-android:2.7.2-SNAPSHOT.

     Required by:
         project : > project :project:pcComponents:core > com.github.uds-se:droidmate-coverage:1.4.2-SNAPSHOT
      Could not resolve de.tud.sse:soot-infoflow-android:2.7.2-SNAPSHOT.
         Unable to load Maven meta-data from https://soot-build.cs.upb.de/nexus/repository/soot-release/de/tud/sse/soot-infoflow-android/2.7.2-SNAPSHOT/maven-metadata.xml.
            Could not get resource 'https://soot-build.cs.upb.de/nexus/repository/soot-release/de/tud/sse/soot-infoflow-android/2.7.2-SNAPSHOT/maven-metadata.xml'.
               Could not GET 'https://soot-build.cs.upb.de/nexus/repository/soot-release/de/tud/sse/soot-infoflow-android/2.7.2-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Repository version policy: RELEASE does not allow metadata in path: de/tud/sse/soot-infoflow-android/2.7.2-SNAPSHOT/maven-metadata.xml

   Could not resolve de.upb.cs.swt:heros:1.1.0-SNAPSHOT.

     Required by:
         project : > project :project:pcComponents:core > com.github.uds-se:droidmate-coverage:1.4.2-SNAPSHOT > ca.mcgill.sable:soot:3.3.0-SNAPSHOT:20190514.152411-8
      Could not resolve de.upb.cs.swt:heros:1.1.0-SNAPSHOT.
         Unable to load Maven meta-data from https://soot-build.cs.upb.de/nexus/repository/soot-release/de/upb/cs/swt/heros/1.1.0-SNAPSHOT/maven-metadata.xml.
            Could not get resource 'https://soot-build.cs.upb.de/nexus/repository/soot-release/de/upb/cs/swt/heros/1.1.0-SNAPSHOT/maven-metadata.xml'.
               Could not GET 'https://soot-build.cs.upb.de/nexus/repository/soot-release/de/upb/cs/swt/heros/1.1.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Repository version policy: RELEASE does not allow metadata in path: de/upb/cs/swt/heros/1.1.0-SNAPSHOT/maven-metadata.xml

**Comment by natanieljr** [comment]
Hi,

Which Java version are you using?

**Comment by pilgun** [comment]
Hi

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

The problem is that the project somehow requests for 2.7.2 soot version from the maven repository. But the highest available is 2.7.1 https://soot-build.cs.upb.de/nexus/#browse/browse:soot-release:de%2Ftud%2Fsse%2Fsoot-infoflow-android

Does it work differently when you git clone and build project yourself in a new location?

**Comment by natanieljr** [comment]
Right.

I think I found the problem.

We used version 2.7.2 which was in the soot-snapshot repository.

However, it seems they removed the infoflow-android from the snapshot repository when they updated the regular infoflow

https://soot-build.cs.upb.de/nexus/#browse/browse:soot-snapshot:de%2Ftud%2Fsse%2Fsoot-infoflow-android

I downgraded to 2.7.1. Please pull the latest version.

**Comment by pilgun** [comment]
I don't see new commits, you probably did not push the update

**Comment by natanieljr** [comment]
Pushed

**Comment by pilgun** [comment]
Thank you! It worked
