### ISSUE TITLE
gradlew build error

### ISSUE THREAD

**Issue by clesmian** [natanieljr/droidmate#12]
I'm not able to build the current version of the project because of a dependency of droidmate-coverage not being resolvable by gradle.

It seems that grade is not able to pull "ca.mcgill.sable:soot:3.3.0".

**Error message of "./gradlew build":**

Execution failed for task ':startScripts'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve ca.mcgill.sable:soot:3.3.0-SNAPSHOT.
     Required by:
         project : > project :project:pcComponents:core > com.github.uds-se:droidmate-coverage:master-SNAPSHOT:1.4.2-SNAPSHOT-g2c9a00e-3
      > Could not resolve ca.mcgill.sable:soot:3.3.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://soot-build.cs.upb.de/nexus/repository/soot-release/ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://soot-build.cs.upb.de/nexus/repository/soot-release/ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://soot-build.cs.upb.de/nexus/repository/soot-release/ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Repository version policy: RELEASE does not allow metadata in path: ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml
      > Could not resolve ca.mcgill.sable:soot:3.3.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/ca/mcgill/sable/soot/3.3.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

Please excuse that my understanding of gradle is pretty limited so I can't give you more detailed information.

**Comment by Hotzkow** [comment]
The snapshot version was removed from the official soot repository, I changed it to the release version. It should build again.

**Comment by clesmian** [comment]
Thank you very much for your help!
