### ISSUE TITLE
Coverage data not generated (again?)

### ISSUE THREAD

**Issue by thlmenezes** [natanieljr/droidmate#13]
Hello, 

I've had the same problem as @chanhduc described in issue #7 

Could someone help me?

I feel like I've tried everything

**Comment by thlmenezes** [comment]
Answered in #7

**Comment by natanieljr** [comment]
Hi, sorry for the late reply. Somehow I'm not receiving github updates. 

Is it working for you again?

**Comment by thlmenezes** [comment]
Yes, I've corrected my code with @chanhduc's help in issue #7 

Can you close this issue?
