### ISSUE TITLE
Adjusting frequency of actions

### ISSUE THREAD

**Issue by DennisTsiang** [natanieljr/droidmate#5]
Hi there, your project seem very useful to me. I was wondering if there is an option to adjust the frequency of the actions via a command line parameter? Looking at `ConfigurationBuilder.kt` I can see `deviceOperationDelay` but I am unsure if this is what I am looking for.

If such an option does not exist, could you point me to where in the codebase I could make this extension?

**Comment by natanieljr** [comment]
Hi,

Could you elaborate on what you mean by frequency of the actions?

Do you want to introduce a fixed delay between the actions or do you want to have the actions triggered at specific times?

**Comment by DennisTsiang** [comment]
Yes, I meant a fixed delay between the actions. For example, 2 seconds between each button press

**Comment by natanieljr** [comment]
Right, 

So, the [actions](https://github.com/uds-se/droidmate/blob/master/project/pcComponents/core/src/main/kotlin/org/droidmate/exploration/actions/WidgetActions.kt#L26) have the possibility of a fixed delay, which we are now using as [0 by default](https://github.com/uds-se/droidmate/blob/master/project/pcComponents/core/src/main/kotlin/org/droidmate/exploration/actions/WidgetActions.kt#L75).

I could have a look on this problem next week or if you want to give it a try, you could add a delay parameter to this _availableActions_ function and have it also as a parameter on the [RandomWidget](https://github.com/uds-se/droidmate/blob/master/project/pcComponents/core/src/main/kotlin/org/droidmate/exploration/strategy/widget/RandomWidget.kt#L203) class, with a default value of 0 not to affect any running item.

**Comment by DennisTsiang** [comment]
Thanks, I'd appreciate it if you'd take a look at it. Probably will be quicker than me trying to implement it myself. 

In the meantime though, I will try out your suggestions and see if I can get it working.

**Comment by natanieljr** [comment]
Update pushed to the DEV branch.

You can use the command line parameter `--Exploration-widgetActionDelay=<DELAY>` if you are using DM's default strategies, otherwise you can use the parameter on your custom strategy.
