### ISSUE TITLE
Instrumenter Class not found error

### ISSUE THREAD

**Issue by chanhduc** [natanieljr/droidmate#6]
I have recently cloned this project yesterday and built it successfully with gradle. I've tried running droitmate and it seemed to be ok. However, when I tried instrumented apk, the problem occurred. 

```bash
Exception in thread "main" java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
	at org.droidmate.coverage.Instrumenter.instrument(Instrumenter.kt:196)
...
```

I also dived in the project's source code and I found there's not any source code related to org.droidmate.coverage.Instrumenter. Does the last commit of this project cause this issue?

Could you please help to fix it?

Thank you.

**Comment by natanieljr** [comment]
Hi,

Yes, there's currently a bug which I'm trying to fix. There is a Gradle configuration error in DM and it's not pulling the necessary Soot repositories for instrumentation.

In the meantime, you can instrument your application using 

https://github.com/uds-se/droidmate-coverage

And then take the instrumented app and run Droidmate.

**Comment by chanhduc** [comment]
Thank you for your quick answer.

I will try this solution.

**Comment by natanieljr** [comment]
Hi, just checking if the solution worked for you.

If so, I'll close this issue

**Comment by chanhduc** [comment]
Thank you @natanieljr . It solved my problem.
