### ISSUE TITLE
Interaction.devicelogs is empty

### ISSUE THREAD

**Issue by chanhduc** [natanieljr/droidmate#8]
Dear,

I tried to use your ActivitySeenSummary model feature but I realized that devicelogs of all interactions are empty.  Do I have to configure anything to record devicelogs for each interaction?

Thank you.

**Comment by natanieljr** [comment]
Hi,

Those logs are created using "inlined" apks, where the API calls are monitored.

The monitor is available at:
https://github.com/uds-se/droidmate-monitor/

You should inline your apk with it to log the start activity calls and should run this inline apk with the flag: `--Deploy-installMonitor=true`

Please note that this feature is highly experimental and works only on Android 6 to 9

**Comment by chanhduc** [comment]
Hi,

After I inline apk, I cannot install the apk on the emulator. The installation process appeared the error: 
`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl661139191.tmp/base.apk has no certificates at entry AndroidManifest.xml]`

From your wiki (https://github.com/uds-se/droidmate/wiki/Monitoring-and-restricting-APIs), you noticed that "Note: Inlined apps do not work on emulators." Is that the reason for this issue?

**Comment by natanieljr** [comment]
Could you attach the apk for debugging?

I haven't seen this error yet and cannot reproduce with the apks which I normally use for testing.

**Comment by natanieljr** [comment]
> From your wiki (https://github.com/uds-se/droidmate/wiki/Monitoring-and-restricting-APIs), you noticed that "Note: Inlined apps do not work on emulators." Is that the reason for this issue?

I forgot to add an answer to this point.

We use the library ArtHook as a proxy between the app and the OS. This library doesn't support x86 architecture, just ARM.

**Comment by natanieljr** [comment]
Assuming everything is working since there was no feedback after the solution
