### ISSUE TITLE
How to generate jar file? Need update of wiki

### ISSUE THREAD

**Issue by michael172849** [natanieljr/droidmate#9]
In the wiki/deploying, it says to use 

> gradlew shadowJar

to generate a runnable jar but apparently, this command does not run successfully. I got this error:

> Task 'shadowJar' not found in root project 'droidmate-2'.

I can successfully run `./gradlew build` and `./gradlew install`. But I don't know how to actually run droidmate.

Also through the entire wiki, droidmate can be run using:
> java -jar DM-2.jar.

Where is this DM-2.jar?? It is not in the repo and not mentioned in the wiki about how to generate it.

**Comment by natanieljr** [comment]
Hi, 

Indeed, the plugin we have to generate Jar had some compatibility issues when we updated the Gradle version.

You can, however, run DM through Gradle with the `./gradlew run` command. Below is an example of this command with arguments to DM.

```
./gradlew run --args="--Selectors-actionLimit=100 --Exploration-apksDir=./apks --Output-outputDir=./out --Exploration-launchActivityDelay=3000 --Exploration-widgetActionDelay=800 --Selectors-randomSeed=1 --Deploy-installApk=true --Deploy-uninstallApk=true --Selectors-pressBackProbability=0.1"
```

**Comment by natanieljr** [comment]
Fixed documentation and re-enabled the shadowJar plugin.

Updated wiki documentation at: https://github.com/uds-se/droidmate/wiki/Deploying
